### ISSUE TITLE
Problem with nested loops

### ISSUE THREAD

**Issue by ctkelley** [JuliaFolds2/OhMyThreads.jl#86] opened 2024-03-16 17:25 UTC
I am trying to get @tasks to work with a nested loop and am able to
find what I need in the docs. Herewith a MWE:

I've tried using ```@set``` but with no luck.

```julia
function looper(n = 10)
    A = rand(n, n)
    for k = 1:n
        A[:, k] .*= 2.0
        @tasks for j = k+1:n
            for i = k+1:n
                A[i, j] -= A[i, k] * A[k, j]
            end
        end
    end
end
```
I run Julia from a directory with only this file in it.

```julia
% julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.10.2 (2024-03-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using OhMyThreads

julia> include("looper.jl")
looper (generic function with 2 methods)

julia> looper()
ERROR: ArgumentError: You must either indicate the desired number of chunks (n) or the target size of a chunk (size).
Stacktrace:
  [1] missing_input_err()
    @ ChunkSplitters ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:118
  [2] getchunk(itr::UnitRange{Int64}, ichunk::Int64; n::Int64, size::Int64, split::Symbol)
    @ ChunkSplitters ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:274
  [3] getchunk
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:273 [inlined]
  [4] getchunk
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:293 [inlined]
  [5] iterate
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:142 [inlined]
  [6] iterate
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:141 [inlined]
  [7] iterate
    @ ./generator.jl:44 [inlined]
  [8] collect(itr::Base.Generator{ChunkSplitters.Chunk{…}, OhMyThreads.Implementation.var"#13#21"{…}})
    @ Base ./array.jl:834
  [9] map(f::Function, A::ChunkSplitters.Chunk{UnitRange{Int64}, ChunkSplitters.FixedCount})
    @ Base ./abstractarray.jl:3313
 [10] _tmapreduce(f::Function, op::Function, Arrs::Tuple{…}, ::Type{…}, scheduler::DynamicScheduler{…}, mapreduce_kwargs::@Kwargs{…})
    @ OhMyThreads.Implementation ~/.julia/packages/OhMyThreads/N9muZ/src/implementation.jl:52
 [11] #tmapreduce#10
    @ ~/.julia/packages/OhMyThreads/N9muZ/src/implementation.jl:33 [inlined]
 [12] tmapreduce
    @ ~/.julia/packages/OhMyThreads/N9muZ/src/implementation.jl:25 [inlined]
 [13] #tforeach#70
    @ ~/.julia/packages/OhMyThreads/N9muZ/src/implementation.jl:180 [inlined]
 [14] macro expansion
    @ ~/.julia/packages/OhMyThreads/N9muZ/src/macro_impl.jl:45 [inlined]
 [15] looper(n::Int64)
    @ Main ~/OMTest/looper.jl:5
 [16] looper()
    @ Main ~/OMTest/looper.jl:2
 [17] top-level scope
    @ REPL[3]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> 
```

**Comment by carstenbauer** [comment] 2024-03-17 07:15
Curious, if we comment out the outer loop it runs without errors:

```julia
using OhMyThreads

function looper(n = 10)
    A = rand(n, n)
    k = 2
    # for k = 1:n
        A[:, k] .*= 2.0
        @tasks for j = k+1:n
            for i = k+1:n
                A[i, j] -= A[i, k] * A[k, j]
            end
        end
    # end
end

looper()
```

**Comment by carstenbauer** [comment] 2024-03-17 07:23
The issue is

```julia
julia> collect(chunks(11:10; n=6))
ERROR: ArgumentError: You must either indicate the desired number of chunks (n) or the target size of a chunk (size).
Stacktrace:
  [1] missing_input_err()
    @ ChunkSplitters ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:118
  [2] getchunk(itr::UnitRange{Int64}, ichunk::Int64; n::Int64, size::Int64, split::Symbol)
    @ ChunkSplitters ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:274
  [3] getchunk
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:273 [inlined]
  [4] getchunk
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:293 [inlined]
  [5] iterate
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:142 [inlined]
  [6] iterate
    @ ~/.julia/packages/ChunkSplitters/R5lnx/src/ChunkSplitters.jl:141 [inlined]
  [7] copyto!(dest::Vector{StepRange{Int64, Int64}}, src::ChunkSplitters.Chunk{UnitRange{Int64}, ChunkSplitters.FixedCount})
    @ Base ./abstractarray.jl:943
  [8] _collect
    @ ./array.jl:765 [inlined]
  [9] collect(itr::ChunkSplitters.Chunk{UnitRange{Int64}, ChunkSplitters.FixedCount})
    @ Base ./array.jl:759
 [10] top-level scope
    @ REPL[32]:1
```

It occurs because for `k=n` you get `k+1:n == n+1:n`.

**Comment by carstenbauer** [comment] 2024-03-17 08:15
Will be fixed by https://github.com/JuliaFolds2/OhMyThreads.jl/pull/88 (in the next release).

**Closed** 2024-03-17 08:22 UTC
Labels: bug, fix scheduled
