### ISSUE TITLE
collect = true leads to a vector of nothing 

### ISSUE THREAD

**Issue by Qiaoyi-Li** [JuliaFolds2/OhMyThreads.jl#105] opened 2024-04-29 14:02 UTC
I tried the following example in [Public API](https://juliafolds2.github.io/OhMyThreads.jl/stable/refs/api/)
```julia
@tasks for i in 1:3
       @set collect=true
       i^2
end
```
and it will return a length-3 vector of nothing.  Note explicit `return i^2` will solve this problem and gives `[1, 4, 9]` correctly. Is this an expected behavior or just a bug?

The julia version is 
```
Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 12 × Apple M2 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 6 on 8 virtual cores
```

**Comment by Qiaoyi-Li** [comment] 2024-04-29 14:44
Note additionally, I tried it with Julia `v1.10.2`, the result is correct.

**Comment by carstenbauer** [comment] 2024-04-29 18:13
We can't reproduce the issue and apparently it works for you on the latest stable Julia version. For these reasons, I'm going to close this.

**Comment by MasonProtter** [comment] 2024-04-29 19:03
> Thanks for replying so quickly.
> 
> ```julia
> using Pkg; pkg"which OhMyThreads"
> ```
> 
> does not seem to be a julia command ? Maybe you mean the version? (`OhMyThreads v0.5.2`)

Yes, sorry I meant `pkg"st OhMyThreads"`. 

I just checked on v1.9.2 and 1.9.4 and and I am able to reproduce the issue. That's quite strange, I wonder what could cause it. I'm going to re-open this because we do claim support for v1.9. I'd say we should either look for a fix, or drop v1.9 support.

**Comment by MasonProtter** [comment] 2024-04-29 19:09
Even more bizarre is that the error only occurs for me when using the macro, not if I copy-paste the macroexpanded code:
```julia
julia> @tasks for i in 1:3
           @set collect=true
           i^2
       end
3-element Vector{Nothing}:
 nothing
 nothing
 nothing

julia> @macroexpand1 @tasks for i in 1:3
           @set collect=true
           i^2
       end
:(let
      begin
          #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:80 =#
          begin
              #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:246 =#
          end
          #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:81 =#
          begin
              #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:266 =#
          end
          #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:82 =#
          nothing
          #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:83 =#
          local function var"#10#mapping_function"(i)
                  #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:57 =#
                  #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:58 =#
                  begin
                      #= REPL[18]:2 =#
                      #= REPL[18]:3 =#
                      i ^ 2
                      #= REPL[18]:4 =#
                  end
              end
          #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:84 =#
          OhMyThreads.tmap(var"#10#mapping_function", 1:3; )
      end
  end)

julia> let
             begin
                 #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:80 =#
                 begin
                     #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:246 =#
                 end
                 #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:81 =#
                 begin
                     #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:266 =#
                 end
                 #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:82 =#
                 nothing
                 #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:83 =#
                 local function var"#10#mapping_function"(i)
                         #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:57 =#
                         #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:58 =#
                         begin
                             #= REPL[18]:2 =#
                             #= REPL[18]:3 =#
                             i ^ 2
                             #= REPL[18]:4 =#
                         end
                     end
                 #= /home/mason/.julia/packages/OhMyThreads/V13wc/src/macro_impl.jl:84 =#
                 OhMyThreads.tmap(var"#10#mapping_function", 1:3; )
             end
         end
3-element Vector{Int64}:
 1
 4
 9
```
but I *do* get the wrong behaviour if I directly `eval` that macroexpanded code:
```julia
julia> eval(begin
           @macroexpand1 @tasks for i in 1:3
               @set collect=true
               i^2
           end
       end)
3-element Vector{Nothing}:
 nothing
 nothing
 nothing
```
That's really spooky. I'm starting to suspect this is a julia-side bug, but it'll require some more digging.

**Comment by carstenbauer** [comment] 2024-08-07 13:43
Although a bit disappointing, I think we should drop 1.9 support given that 1.10 is the new LTS. (FWIW, I'm doing the same for ThreadPinning.jl in the next version.)

**Comment by MasonProtter** [comment] 2024-08-07 14:15
Yeah lets do that.

**Comment by carstenbauer** [comment] 2024-08-15 12:19
Support for Julia < 1.10 will be dropped in version 0.6 (to be released soon).

**Closed by carstenbauer** 2024-08-15 12:19 UTC
